accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('<int:pk>/profile/', views.profile, name="profile"),
]

follows/urls.py
from django.urls import path
from . import views

app_name = "follows"
urlpatterns = []

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
  path('create/', views.create, name="create"),
  path('<int:pk>/', views.product_detail, name="product_detail"),
  path('<int:pk>/delete/', views.delete, name="delete"),
  path('<int:pk>/update/', views.update, name="update"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
    path('follows/', include("follows.urls")),
]

accounts/models.py
from django.db import models

follows/models.py
from django.db import models
from django.contrib.auth.models import User

class Follow(models.Model):
  follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
  followed_user = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)

class Meta:
  unique_together = ('follower', 'followed_user')

def __str__(self):
  return f'{self.follower} follows {self.followed_user}'

hashtags/models.py
from django.db import models

# Create your models here.

jjims/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
  user_id = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=50)
  content = models.TextField()
  price = models.IntegerField()
  views = models.IntegerField(default=0)
  jjims = models.IntegerField(default=0)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.urls import reverse

class CustomUserChangeForm(UserChangeForm):
  class Meta:
    model = get_user_model()
    fields = {
      "first_name",
      "last_name",
      "email",
    }
  
  def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      if self.fields.get("password"):
          password_help_text = (
              "You can change the password " '<a href="{}">here</a>.'
          ).format(f"{reverse('accounts:change_password')}")
          self.fields["password"].help_text = password_help_text

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    exclude = ['user_id', 'views', 'jjims']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserChangeForm


def login(request):
  if request.method == "POST":
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      auth_login(request, form.get_user())
      next_url = request.GET.get("next") or "index"
      return redirect(next_url)
  else:
    form = AuthenticationForm()
  context = {"form": form}
  return render(request, "accounts/login.html", context)

@require_POST
def logout(request):
  if request.user.is_authenticated:
    auth_logout(request)
  return redirect("index")

@require_http_methods(["GET", "POST"])
def signup(request):
  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      auth_login(request, user)
      return redirect("index")
  else:
    form = UserCreationForm()
  context = {"form": form}
  return render(request, "accounts/signup.html", context)

@require_POST
def delete(request):
  if request.user.is_authenticated:
    request.user.delete()
    auth_logout(request)
  return redirect("index")

@require_http_methods(["GET", "POST"])
def update(request):
  if request.method == "POST":
    form = CustomUserChangeForm(request.POST, instance=request.user)
    if form.is_valid():
      form.save()
      return redirect("index")
  else:
    form = CustomUserChangeForm(instance = request.user)
  context = {"form": form}
  return render(request, "accounts/update.html", context)

def change_password(request):
  if request.method == "POST":
    form = PasswordChangeForm(request.user, request.POST)
    if form.is_valid():
      form.save()
      update_session_auth_hash(request, form.user)
      return redirect("index")
  else:
    form = PasswordChangeForm(request.user)
  context = {"form": form}
  return render(request, "accounts/change_password.html", context)

def profile(request, pk):
  return render(request, "accounts/profile.html")

follows/views.py
from django.shortcuts import render

# Create your views here.

hashtags/views.py
from django.shortcuts import render

# Create your views here.

jjims/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .models import Product
from .forms import ProductForm


# 홈화면 겸 등록 상품 목록
def index(request):
  products = Product.objects.all().order_by("-pk")
  context = {"products": products}
  return render(request, "products/index.html", context)

# 상세 페이지
def product_detail(request, pk):
  product = get_object_or_404(Product, pk=pk)
  product.views += 1
  product.save()
  context = {"product": product}
  return render(request, "products/product_detail.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def create(request):
  if request.method == "POST":
    form = ProductForm(request.POST)
    if form.is_valid():
      product = form.save()
      return redirect("products:product_detail", product.pk)
    return redirect("products:create")
  else:
    form = ProductForm()
  context = {"form": form}
  return render(request, "products/create.html", context)

# 글 삭제
@login_required
@require_POST
def delete(request, pk):
  product = Product.objects.get(pk=pk)
  product.delete()
  return redirect("index")

# 글 수정
@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
  if request.method == "POST":
    title = request.POST.get("title")
    content = request.POST.get("content")
    price = request.POST.get("price")

    product = Product.objects.get(pk=pk)
    product.title = title
    product.content = content
    product.price = price
    product.save()
    return redirect("products:product_detail", pk=product.pk)
  else:
    product = Product.objects.get(pk=pk)
    context = {"product": product}
    return render(request, "products/update.html", context)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">비밀번호 변경</button>
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html"%}
{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" vlaue="로그인">
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<h1>회원가입</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token%}
  {{ form.as_p }}
  <button type="submit">회원가입</button>
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block content %}
<h1>회원정보 수정</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">수정</button>
</form>
{% endblock content %}

products/templates/products/create.html
{% extends "base.html" %}
{% block content %}
<h1>새 상품 등록</h1>
<form action="{% url 'products:create' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">등록</button>
</form>
<a href="{% url 'index' %}">취소</a>
{% endblock content %}

products/templates/products/index.html
{% extends "base.html" %}
{% block content %}
<h1>상품 목록</h1>
{% for product in products %}
<a>[ {{ product.id }} ]</a>
<a href="{% url 'products:product_detail' product.id %}">{{ product.title }}</a>
<hr>
{% endfor %}

<a href="{% url 'index' %}">이동</a>
<a href="{% url 'products:create' %}">상품 등록</a>
{% endblock content %}

products/templates/products/new.html
{% extends "base.html" %}
{% block content %}
<h1>새 상품 등록</h1>
<form action="{% url 'products:create' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">등록</button>
</form>
<a href="{% url 'index' %}">취소</a>
{% endblock content %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>상품 상세</h1>
<h3>{{ product.title }}</h3>
<p>조회수: {{ product.views }}</p>
<p>작성일: {{ product.created_at }}</p>
<p>가격: {{ product.price }} &#8361;</p>
<img style="width:50%" src="{% static 'products/product.jpg' %}">
<p>{{ product.content }}</p>
<a href="{% url 'products:update' product.pk %}">수정</a>
<form action="{% url 'products:delete' product.pk %}" method="POST">
  {% csrf_token %}
  <button type="submit">삭제</button>
</form>
<a href="{% url 'index' %}">뒤로가기</a>
{% endblock content %}

products/templates/products/update.html
{% extends "base.html" %}
{% block content %}
<h1>상품 수정</h1>
<form action="{% url 'products:update' product.pk %}" method="POST">
  {% csrf_token %}
  <label for="title">Title: </label>
  <input type="text" id="title" name="title" value="{{ product.title }}"><br><br>
  <label for="content">Content: </label>
  <textarea id="content" name="content" cols="30" rows="10">{{ product.content }}</textarea><br><br>
  <label for="price">Price: </label>
  <input type="number" value="{{ product.price }}"><br><br>
  <button type="submit">등록</button>
  <a href="{% url 'products:product_detail' product.pk %}">취소</a>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="navbar">
    {% if request.user.is_authenticated %}
    <div>Hello! {{ user.username }}</div>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <button type="submit">로그아웃</button>
    </form>

    <a href="{% url 'accounts:update' %}">회원정보 수정</a>

    <form action="{% url 'accounts:delete' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
    {% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    
  </div>
  <div class="container">
    {% block content %}
    {% endblock content %} 
  </div> 
</body>
</html>